version: 2.1

workflows:
  access-gpio:
    jobs:
      # - docker-build
      - docker-test

jobs:
  docker-test:
    machine: true
    resource_class: ylin-demos-namespace/ylin-resource-class
    steps:
      - checkout
      # - run:
      #     name: Run test
      #     command: robot .
      - run:
          name: Run test
          command: sudo docker build -t docker-test . && sudo docker run --rm --privileged docker-test
      

  # docker-build:
  #   docker:
  #     - image: cimg/python:3.7
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install
  #         command:  sudo apt-get update && sudo apt-get install python3-pip && pip install RPi.GPIO && pip3 install robotframework && pip3 install elasticsearch && python3 -m pip install .
  #     - run:
  #         name: Run
  #         command:  robot .