version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  access-USB:
    jobs:
      - build-and-test


jobs:
  build-and-test: 
    machine:
      image: ubuntu-2004:current
    # resource_class: large
    # docker:
    #   - image: cimg/python:3.8
    steps:
      - checkout
      # - python/install-packages:
      #     pkg-manager: pip
      - run:
          name: Install
          # This assumes pytest is installed via the install-package step above
          command:  sudo apt-get update && sudo apt-get install usbutils
      - run:
          name: Install2
          # This assumes pytest is installed via the install-package step above
          command:  ls 
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: python3 test.py
