version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  access-USB:
    jobs:
      - build-and-test


jobs:
  build-and-test: 
    machine:
      image: ubuntu-2004:current
    resource_class: large
    # docker:
    #   - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install
          command:  sudo apt-get update && sudo apt-get install usbutils
      - run:
          name: Run tests
          command: lsusb
